from flask import Flask, send_from_directory, jsonify
import scraping
app = Flask(__name__)

@app.route("/")
def index():
    return send_from_directory('client/public', 'index.html')

# Serve static files generated by svelte
@app.route("/<path:path>")
def home(path):
    return send_from_directory('client/public', path)

@app.route("/api/baths")
def get_bath_info():
    events = [dict(event, name=scraping.baths[bath_id])
                for bath_id in scraping.baths.keys()
                for event in scraping.get_slot_info(bath_id, 2022, 2)]
    return jsonify(events)
    return jsonify([
    {
        "bath_id": 1, 
        "date": "Sat, 26 Feb 2022 00:00:00 GMT", 
        "end_time": "08:30", 
        "from_date": "", 
        "id": "2561103", 
        "link": "https://pretix.eu/Baeder/1/2561103/", 
        "name": "Stadtbad Mitte", 
        "start_time": "06:30", 
        "state": "available"
    }, 
    {
        "bath_id": 1, 
        "date": "Sat, 26 Feb 2022 00:00:00 GMT", 
        "end_time": "10:45", 
        "from_date": "", 
        "id": "2561104", 
        "link": "https://pretix.eu/Baeder/1/2561104/", 
        "name": "Stadtbad Mitte", 
        "start_time": "08:45", 
        "state": "soldout"
    }, 
    {
        "bath_id": 1, 
        "date": "Sat, 27 Feb 2022 00:00:00 GMT", 
        "end_time": "13:00", 
        "from_date": "", 
        "id": "2561105", 
        "link": "https://pretix.eu/Baeder/1/2561105/", 
        "name": "Stadtbad Mitte", 
        "start_time": "11:00", 
        "state": "soldout"
    }, 
    {
        "bath_id": 1, 
        "date": "Sat, 27 Feb 2022 00:00:00 GMT", 
        "end_time": "13:00", 
        "from_date": "", 
        "id": "2561105", 
        "link": "https://pretix.eu/Baeder/1/2561105/", 
        "name": "Stadtbad Mitte", 
        "start_time": "11:00", 
        "state": "soldout"
    }, 
    {
        "bath_id": 1, 
        "date": "Sat, 27 Feb 2022 00:00:00 GMT", 
        "end_time": "13:00", 
        "from_date": "", 
        "id": "2561105", 
        "link": "https://pretix.eu/Baeder/1/2561105/", 
        "name": "Stadtbad Mitte", 
        "start_time": "11:00", 
        "state": "soldout"
    }, 
    {
        "bath_id": 1, 
        "date": "Sat, 27 Feb 2022 00:00:00 GMT", 
        "end_time": "13:00", 
        "from_date": "", 
        "id": "2561105", 
        "link": "https://pretix.eu/Baeder/1/2561105/", 
        "name": "Stadtbad Mitte", 
        "start_time": "11:00", 
        "state": "soldout"
    }, 
    {
        "bath_id": 1, 
        "date": "Sat, 27 Feb 2022 00:00:00 GMT", 
        "end_time": "13:00", 
        "from_date": "", 
        "id": "2561105", 
        "link": "https://pretix.eu/Baeder/1/2561105/", 
        "name": "Stadtbad Mitte", 
        "start_time": "11:00", 
        "state": "soldout"
    }, 
    {
        "bath_id": 1, 
        "date": "Sat, 27 Feb 2022 00:00:00 GMT", 
        "end_time": "13:00", 
        "from_date": "", 
        "id": "2561105", 
        "link": "https://pretix.eu/Baeder/1/2561105/", 
        "name": "Stadtbad Mitte", 
        "start_time": "11:00", 
        "state": "reserved"
    }, 
    {
        "bath_id": 1, 
        "date": "Sat, 27 Feb 2022 00:00:00 GMT", 
        "end_time": "13:00", 
        "from_date": "", 
        "id": "2561105", 
        "link": "https://pretix.eu/Baeder/1/2561105/", 
        "name": "Stadtbad Mitte", 
        "start_time": "11:00", 
        "state": "soldout"
    }, 
    {
        "bath_id": 1, 
        "date": "Sat, 27 Feb 2022 00:00:00 GMT", 
        "end_time": "15:15", 
        "from_date": "", 
        "id": "2561106", 
        "link": "https://pretix.eu/Baeder/1/2561106/", 
        "name": "Stadtbad Mitte", 
        "start_time": "13:15", 
        "state": "soldout"
    }])

if __name__ == "__main__":
    app.run(debug=True)
