from flask import Flask, send_from_directory
from scraping.lib import get_slot_info
app = Flask(__name__)

@app.route("/")
def base():
    return send_from_directory('client/public', 'index.html')

# Serve static files generated by svelte
@app.route("/<path:path>")
def home(path):
    return send_from_directory('client/public', path)

@app.route("/get_bath_info")
def get_bath_info():
    events = get_slot_info(2, 2022, 2)
    return str(events)

if __name__ == "__main__":
    app.run(debug=True)
