import os
import csv
from flask import Flask, send_from_directory, jsonify
import scraping
app = Flask(__name__)

@app.route("/")
def base():
    return send_from_directory('client/public', 'index.html')

# Serve static files generated by svelte
@app.route("/<path:path>")
def home(path):
    return send_from_directory('client/public', path)

@app.route("/get_bath_info")
def get_bath_info():
    events = [dict(event, name=scraping.baths[bath_id])
                for bath_id in scraping.baths.keys()
                for event in scraping.get_slot_info(bath_id, 2022, 2)]
    return jsonify(events)

if __name__ == "__main__":
    app.run(debug=True)
